name: .NET

on:
  push:
    branches: [ "master" ]
    tags:
      - "*.*.*"
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, target: linux-x64, platform: linux-x64 }
          - { os: macos-latest, target: osx-x64, platform: darwin-x64 }
          - { os: macos-latest, target: osx-arm64, platform: darwin-arm64 }
          - { os: windows-latest, target: win-x64, platform: win32-x64}
    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -r ${{ matrix.target }} -c Release -o ${{ github.workspace }}/artifact 
    - name: Upload
      uses: actions/upload-artifact@v4
      with: 
        name: ${{ matrix.platform }}
        path: ${{ github.workspace }}/artifact/
  release:
    name: Upload Release
    needs: [build]
    runs-on: [ubuntu-latest]
    steps:
      - name: Download
        uses: actions/download-artifact@v5
      - name: Display structure of downloaded files
        run: ls -R
      - name: zip win32-x64
        uses: TheDoctor0/zip-release@v0.2.1
        with:
          filename: win32-x64.zip
          path: win32-x64
      - name: zip linux-x64
        uses: TheDoctor0/zip-release@v0.2.1
        with: 
          filename: linux-x64.zip
          path: linux-x64
      - name: tar linux-64
        run: tar -czvf linux-x64.tar.gz linux-x64
      - name: zip darwin-x64
        uses: TheDoctor0/zip-release@v0.2.1
        with:
          filename: darwin-x64.zip
          path: darwin-x64
      - name: zip darwin-arm64
        uses: TheDoctor0/zip-release@v0.2.1
        with: 
          filename: darwin-arm64.zip
          path: darwin-arm64

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: EmmyLuaUnity
          draft: false
          generate_release_notes: true
          files: |
            linux-x64.zip
            linux-x64.tar.gz
            darwin-x64.zip
            darwin-arm64.zip
            win32-x64.zip
          token: ${{ secrets.RELEASE }}